[package]
name = "apfp"
version = "0.1.0"
edition = "2024"

[features]
default = []
short-circuit = []

[dependencies]
alloca = "0.4.0"
num = { version = "0.4", features = [] }
num-bigint = "0.4"
num-rational = "0.4"

[dev-dependencies]
quickcheck = "1"
ntest = "0.9"
num-traits = "0.2"
robust = "1.2.0"
geometry-predicates = "0.3"
criterion = "0.7.0"

[patch.crates-io]
geometry-predicates = { path = "vendor/geometry-predicates" }

[[bench]]
name = "orient2d_bench"
harness = false
