[package]
name = "apfp"
version = "0.1.0"
edition = "2024"

[features]
default = []
short-circuit = []

[dependencies]
num = { version = "0.4", features = [] }

[dev-dependencies]
quickcheck = "1"
ntest = "0.9"
num-bigint = "0.4"
num-rational = "0.4"
num-traits = "0.2"
robust = "1.2.0"
criterion = "0.7.0"

[[bench]]
name = "orient2d_bench"
harness = false
